---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/kisamoto/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/github.com/kisamoto/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .macos
  - .vimrc
  - .tmux.conf

homebrew_installed_packages:
  - autoconf
  - pt
  - zsh
  - bash-completion
  - git
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - npm
  - nvm
  - ssh-copy-id
  - tree
  - watch
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - ffmpeg
  - cowsay
  - youtube-dl
  - dos2unix
  - htop
  - tmux
  - trash
  - speedtest-cli
  - thefuck
  - fortune
  - imagemagick
  - python3
  - z
  - terraform
  - awscli
  - openshift-cli

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - vivaldi
  - private-internet-access
  - docker
  - firefox
  - google-chrome
  - handbrake
  - macvim
  - nvalt
  - skitch
  - slack
  - sublime-text
  - vagrant
  - virtualbox
  - skype
  - mattermost
  - flux
  - dash
  - visual-studio-code
  - iterm2
  - onedrive
  - caffeine
  - spotify
  - the-unarchiver
  - shiftit
  - intellij-idea
  - datagrip
  - pycharm
  - webstorm
  - appcode
  - java

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""
