---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/kisamoto/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/github.com/kisamoto/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .gitignore
  - .inputrc
  - .macos
  - .vimrc
  - .tmux.conf
  - .zshrc
  - .zshrc.pre-oh-my-zsh

homebrew_installed_packages:
  - autoconf
  - android-sdk
  - awscli
  - azure-cli
  - bash-completion
  - cookiecutter
  - cowsay
  - dos2unix
  - exiftool
  - ffmpeg
  - fortune
  - gcc
  - git
  - glide
  - go
  - gpg
  - htop
  - httpie
  - hugo
  - imagemagick
  - iperf
  - lego
  - libevent
  - mosh
  - nmap
  - node
  - nvm
  - openshift-cli
  - openssl
  - pt
  - pv
  - pwgen
  - python3
  - readline
  - reattach-to-user-namespace # for tmux
  - source-to-image
  - speedtest-cli
  - sqlite
  - ssh-copy-id
  - stormssh
  - terraform
  - thefuck
  - tmux
  - trash
  - tree
  - watch
  - wget
  - wrk
  - yarn
  - youtube-dl
  - z
  - zsh

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcode
  - android-sdk
  - caffeine
  - dash
  - datagrip
  - docker
  - firefox
  - flux
  - google-chrome
  - handbrake
  - intellij-idea
  - iterm2
  - java
  - macvim
  - mattermost
  - nvalt
  - onedrive
  - pycharm
  - shiftit
  - skitch
  - skype
  - slack
  - spotify
  - sublime-text
  - the-unarchiver
  - vagrant
  - virtualbox
  - visual-studio-code
  - vivaldi
  - vlc
  - webstorm

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 824183456, name: "Affinity Photo (1.6.6)"}
  - { id: 572526628, name: "Zeitraffer (1.1.0)"}
  - { id: 692867256, name: "Simplenote (1.1.8)"}
  - { id: 497799835, name: "Xcode (9.1)"}
  - { id: 734418810, name: "SSH Tunnel (16.07)"}
  - { id: 409183694, name: "Keynote (7.3.1)"}
  - { id: 931134707, name: "Wire (3.1)"}
  - { id: 823766827, name: "OneDrive (17.3.7078)"}
  - { id: 452695239, name: "QREncoder (1.5)"}
  - { id: 912423770, name: "Command & Conquer Generals Deluxe Edition (1.1.2)"}

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
